apiVersion: apps/v1
kind: Deployment
metadata:
  name: txt2img-backend
  namespace: model-serving
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: txt2img-backend
  template:
    metadata:
      labels:
        app: txt2img-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.repository }}/txt2img_backend:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.backendPort }}
        env:
        - name: CREDENTIAL_JSON_FILE_NAME
          value: "{{ .Values.env.CREDENTIAL_JSON_FILE_NAME }}"
        - name: NEXT_PUBLIC_BACKEND_URL
          value: "{{ .Values.env.NEXT_PUBLIC_BACKEND_URL }}"
        - name: STORAGE_BUCKET_NAME
          value: "{{ .Values.env.STORAGE_BUCKET_NAME }}"
        - name: SECRET_KEY
          value: "{{ .Values.env.SECRET_KEY }}"
        - name: DATABASE_ENGINE
          value: "{{ .Values.env.DATABASE_ENGINE }}"
        - name: DATABASE_NAME
          value: "{{ .Values.env.DATABASE_NAME }}"
        - name: DATABASE_USER
          value: "{{ .Values.env.DATABASE_USER }}"
        - name: DATABASE_PASSWORD
          value: "{{ .Values.env.DATABASE_PASSWORD }}"
        - name: DATABASE_HOST
          value: "{{ .Values.env.DATABASE_HOST }}"
        - name: DATABASE_PORT
          value: "{{ .Values.env.DATABASE_PORT }}"