
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
  namespace: model-serving
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: {{ .Release.Name }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}" 
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_CREDENTIAL_JSON_FILE_NAME
              value: {{ .Values.frontend.env.NEXT_PUBLIC_CREDENTIAL_JSON_FILE_NAME }}
            - name: NEXT_PUBLIC_STORAGE_BUCKET_NAME
              value: {{ .Values.frontend.env.NEXT_PUBLIC_STORAGE_BUCKET_NAME }}
            - name: NEXT_PUBLIC_SECRET_KEY
              value: {{ .Values.frontend.env.NEXT_PUBLIC_SECRET_KEY }}
            - name: NEXT_PUBLIC_DATABASE_ENGINE
              value: {{ .Values.frontend.env.NEXT_PUBLIC_DATABASE_ENGINE }}
            - name: NEXT_PUBLIC_DATABASE_NAME
              value: {{ .Values.frontend.env.NEXT_PUBLIC_DATABASE_NAME }}
            - name: NEXT_PUBLIC_DATABASE_USER
              value: {{ .Values.frontend.env.NEXT_PUBLIC_DATABASE_USER }}
            - name: NEXT_PUBLIC_DATABASE_PASSWORD
              value: {{ .Values.frontend.env.NEXT_PUBLIC_DATABASE_PASSWORD }}
            - name: NEXT_PUBLIC_DATABASE_HOST
              value: {{ .Values.frontend.env.NEXT_PUBLIC_DATABASE_HOST }}
            - name: NEXT_PUBLIC_DATABASE_PORT
              value: {{ .Values.frontend.env.NEXT_PUBLIC_DATABASE_PORT }}
          volumeMounts:
            - name: credential-json
              mountPath: /app/namsee_key.json
              subPath: namsee_key.json
      volumes:
        - name: credential-json
          configMap:
            name: namsee-key-config
