replicaCount: 2

image:
  repository: kevvn
  tag: 0.0.1
  pullPolicy: Always

service:
  type: ClusterIP
  frontendPort: 3000
  backendPort: 8000

env:
  CREDENTIAL_JSON_FILE_NAME: /app/namsee_key.json
  NEXT_PUBLIC_BACKEND_URL: http://txt2img-backend:8000

configMap:
  name: txt2img-config